language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
